name: release
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache target
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Dependencies
        run: yarn
      - name: Test
        run: yarn test


  build:
    runs-on: ubuntu-latest
    needs: run
    if: github.event.pull_request.merged == true || startsWith(github.event.head_commit.message, ':bookmark:')
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache target
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Dependencies
        run: yarn
      - name: Publish
        run: |
          npm set registry --scope=@getdelta https://npm.pkg.github.com/getdelta
          npm set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          yarn publish --non-interactive
